# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '14.0'
#source 'https://github.com/CocoaPods/Specs.git'
target 'frontend' do
  # Comment the next line if you don't want to use dynamic frameworks 

 use_frameworks!

  # Pods for frontend
pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'
pod 'Kingfisher', '~> 6.0'
end
